version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    reviewers:
      - chiranjeet-baruah

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    reviewers:
      - chiranjeet-baruah