name: TaskFlow CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        go-version: [ '1.24.x' ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    services:
      # Redis service for backend tests
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Install Redis (macOS)
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          brew install redis
          brew services start redis

      - name: Install Redis (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          # Using Memurai as Redis alternative on Windows for CI
          choco install memurai-developer
          Start-Service Memurai

      - name: Get dependencies
        run: go mod download

      - name: Run tests
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage report
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.txt
          flags: unittests
          name: codecov-umbrella
          # If you use a Codecov token, uncomment and set the secret:
          # token: ${{ secrets.CODECOV_TOKEN }}

  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
          cache: true

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6.0.1
        with:
          # Optional: version of golangci-lint to use in form of v1.2.3, defaults to latest if not set
          version: v1.59.1 # Pinned version for consistency
          args: --timeout=5m

  build-examples:
    name: Build Examples
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: [ test, lint ]
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
          cache: true

      - name: Build examples
        run: |
          set -e # Exit immediately if a command exits with a non-zero status.
          for dir in examples/*; do
            if [ -d "$dir" ]; then
              echo "Building $dir..."
              (cd "$dir" && go build -v)
            fi
          done